import * as _cfworker_json_schema from '@cfworker/json-schema';

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
/**
 * Bibliographic Reaction Object (BRO)의 JSON-LD 네이티브 원시 스키마.
 */
type BibliographicReactionObjectBROV10 = BroItemList | BroArticle | BroAbstract;
/**
 * UUID v4, v5, v7을 수용하는 정규화된 범용 고유 식별자 URN 포맷.
 */
type UrnUuidOnly = string;
/**
 * RFC 3339 기반 타임스탬프 강제 규격. Z 또는 오프셋 명시를 누락한 경우 DB 데이터 오염으로 간주하여 인입을 차단함.
 */
type StrictDateTime = string;
/**
 * [CREATOR_ENTITIES] 작성자 엔티티 다형성 계층. 공공 및 법인은 @id 강제 검증, 개인은 수집 파편화 대응을 위한 선택적 @id 허용, 익명은 추적 불가능한 작성자 데이터의 유실 방지 Fallback.
 */
type CreatorRoot = CreatorPerson$1 | CreatorAnonymous$1 | CreatorGovernment$1 | CreatorCorporation$1 | CreatorOrganization$1 | CreatorSoftware$1;
/**
 * BCP 47 / ISO 639 언어 코드 목록.
 */
type LanguageArray = string[];
/**
 * 분류용 핵심어 목록.
 */
type KeywordsArray = string[];
/**
 * Schema.org 표준 PropertyValue 기반 동적 메타데이터 확장 컨테이너. 도서관이나 서비스별로 파편화된 커스텀 메타데이터(예: 평점, 완독 여부, 추천 연령 등)를 스키마를 오염시키지 않고 수용함. NoSQL이나 RDBMS의 JSON 컬럼에서 완벽한 기계적 인덱싱이 가능함.
 */
type AdditionalPropertyArray = {
    "@type": "PropertyValue";
    /**
     * 동적 속성의 식별 키(Key)
     */
    name: string;
    /**
     * 동적 속성의 값(Value). 원시 타입 및 객체 허용.
     */
    value: {
        [k: string]: unknown;
    };
    [k: string]: unknown;
}[];
type UrnIdentifier = {
    [k: string]: unknown;
} | {
    [k: string]: unknown;
} | {
    [k: string]: unknown;
} | {
    [k: string]: unknown;
} | {
    [k: string]: unknown;
} | {
    [k: string]: unknown;
};
type UrnIdentifier1 = string;
/**
 * 순수 본문 문자열 (주로 Markdown 구조). YAML Frontmatter 캡슐화를 전면 폐기함. 인입 파이프라인에서 본 필드 내의 메타데이터 은닉을 감지할 경우 페이로드 수용을 거부(Reject)하며, 모든 메타 속성은 JSON의 1급 객체 또는 additionalProperty로 분리 추출되어야 함.
 */
type PureText = string;
/**
 * 다중 타겟 문서 큐레이션을 위한 영속적 컨테이너 엔티티 (ItemList).
 */
interface BroItemList {
    "@context": "https://schema.org";
    "@type": "ItemList";
    "@id": UrnUuidOnly;
    /**
     * 리스트 컨테이너의 고유 명칭.
     */
    name?: string;
    dateCreated: StrictDateTime;
    /**
     * RFC 3339 기반 타임스탬프 강제 규격. Z 또는 오프셋 명시를 누락한 경우 DB 데이터 오염으로 간주하여 인입을 차단함.
     */
    dateModified?: string;
    /**
     * 에그리거트 루트의 변경 이력 추적 및 낙관적 락(Optimistic Locking) 검증을 위한 버전 해시 또는 시퀀스 넘버.
     */
    version?: string | number;
    /**
     * @minItems 1
     */
    creator: [CreatorRoot, ...CreatorRoot[]];
    /**
     * 리스트에 포함된 개별 문서(Article 등)의 식별자 목록. 직접 내포(Embedding) 금지. 데이터 단편화 방지 및 URN 식별자 정규화를 위해 철저히 포인터 기반 참조로 격리함.
     */
    itemListElement: {
        "@id": UrnUuidOnly;
        [k: string]: unknown;
    }[];
    inLanguage?: LanguageArray;
    keywords?: KeywordsArray;
    additionalProperty?: AdditionalPropertyArray;
    [k: string]: unknown;
}
interface CreatorPerson$1 {
    "@type": "Person";
    name: string;
    /**
     * 인증된 사용자에 한해 부여되는 URN/ORCID 식별자. 파편화된 외부 데이터 스크래핑 인입 시 생략을 허용함.
     */
    "@id"?: UrnUuidOnly | {
        [k: string]: unknown;
    };
}
/**
 * 네트워크 인입 단말 혹은 수집 파이프라인에서 작성자 엔티티 추적에 실패할 경우, null/undefined로 인한 스키마 크래시를 방지하는 Fallback 타입.
 */
interface CreatorAnonymous$1 {
    "@type": "Anonymous";
    name?: string;
}
interface CreatorGovernment$1 {
    "@type": "GovernmentOrganization";
    name: string;
    "@id": UrnUuidOnly | {
        [k: string]: unknown;
    };
}
interface CreatorCorporation$1 {
    "@type": "Corporation";
    name: string;
    "@id": UrnUuidOnly | {
        [k: string]: unknown;
    };
}
interface CreatorOrganization$1 {
    "@type": "Organization";
    name: string;
    "@id": UrnUuidOnly | {
        [k: string]: unknown;
    };
}
interface CreatorSoftware$1 {
    "@type": "SoftwareApplication";
    name: string;
    softwareVersion?: string;
    "@id": {
        [k: string]: unknown;
    };
}
/**
 * 단일 파생 문서(Article) 처리를 위한 영속성 스키마. 기존 YAML 프론트매터 속성을 스키마 최상위 프로퍼티로 추출하여 검색 엔진 및 DB 인덱서의 직접 접근을 허용함.
 */
interface BroArticle {
    "@context": "https://schema.org";
    "@type": "Article";
    "@id": UrnUuidOnly;
    /**
     * 파생 문서 자체의 제목. 시스템 반환 시 Article 엔티티의 최상위 명칭으로 사용됨.
     */
    name?: string;
    /**
     * 현재 문서가 타겟팅(about)하고 있는 원본 코어 저작물의 텍스트 명칭(name). 원문 URN 참조가 실패하거나 지연 로딩될 경우의 디그레이드(Degrade) 처리를 위한 역정규화 데이터. 스키마 전역의 명명 규칙(Naming Convention) 통일성에 따라 Title 대신 Name을 접미사로 강제함.
     */
    aboutName?: string;
    /**
     * 현재 문서가 타겟팅하는 원본 코어 저작물의 원작자 텍스트 표기.
     */
    aboutCreator?: string;
    /**
     * 현재 파생 문서 작성자의 크레딧 라인 표기.
     */
    articleByline?: string;
    dateCreated: StrictDateTime;
    dateModified?: StrictDateTime;
    datePublished?: StrictDateTime;
    version?: string | number;
    /**
     * 파생 문서가 타겟팅하는 코어 저작물 엔티티의 식별자 묶음. 다중 판본 바인딩 시 복수 원소를 허용함.
     *
     * @minItems 1
     */
    about: [TerminalIdentifier, ...TerminalIdentifier[]];
    text: PureText;
    inLanguage?: LanguageArray;
    keywords?: KeywordsArray;
    /**
     * 관련 이미지 URL 배열.
     */
    image?: string[];
    /**
     * 참고 문헌 또는 원문 URL 목록.
     */
    citation?: string[];
    /**
     * 현재 문서(Article)에 종속된 파생 요약본의 식별자(URN) 배열. 1:N 구조의 디스크 중복 적재를 막기 위한 식별자 참조. 본문 내포 절대 금지.
     */
    abstract?: {
        "@id": UrnUuidOnly;
        [k: string]: unknown;
    }[];
    /**
     * @minItems 1
     */
    creator: [CreatorRoot, ...CreatorRoot[]];
    additionalProperty?: AdditionalPropertyArray;
    [k: string]: unknown;
}
/**
 * 순환 참조(Billion Laughs 등) 무한 루프 렌더링 공격을 원천 차단하기 위해 계층 깊이를 제한한 터미널 식별 객체.
 */
interface TerminalIdentifier {
    "@type": "Article" | "CreativeWork";
    /**
     * [BASE_PRIMITIVES: 원시 데이터 계층 식별자] 시스템 레벨의 소문자 URN Scheme 정규화를 전제로 한 정규식 집합.
     */
    identifier: UrnIdentifier & UrnIdentifier1;
}
/**
 * 구조화된 요약 데이터. isBasedOn 속성을 통해 원본 역참조.
 */
interface BroAbstract {
    "@context": "https://schema.org";
    "@type": "CreativeWork";
    "@id": UrnUuidOnly;
    /**
     * 요약 데이터의 텍스트 명칭(제목). 스키마 전역의 식별 표제 단일화 정책에 따라 name 속성을 할당함.
     */
    name?: string;
    dateCreated: StrictDateTime;
    dateModified?: StrictDateTime;
    version?: string | number;
    text: PureText;
    inLanguage?: LanguageArray;
    keywords?: KeywordsArray;
    /**
     * 관련 이미지 URL 배열.
     */
    image?: string[];
    /**
     * 참고 문헌 또는 원문 URL 목록.
     */
    citation?: string[];
    /**
     * @minItems 1
     */
    creator: [CreatorRoot, ...CreatorRoot[]];
    /**
     * 이 요약이 기반하고 있는 원본 엔티티(Article 또는 도서 등 CreativeWork)의 단방향 외부 식별자 포인터.
     *
     * @minItems 1
     */
    isBasedOn: [TerminalIdentifier, ...TerminalIdentifier[]];
    additionalProperty?: AdditionalPropertyArray;
    [k: string]: unknown;
}

var $schema = "https://json-schema.org/draft/2020-12/schema";
var $id = "https://schema.slat.or.kr/bro/v1.0/schema.json";
var title = "Bibliographic Reaction Object (BRO) v1.0";
var description = "Bibliographic Reaction Object (BRO)의 JSON-LD 네이티브 원시 스키마.";
var type = "object";
var oneOf = [
	{
		$ref: "#/$defs/BroItemList"
	},
	{
		$ref: "#/$defs/BroArticle"
	},
	{
		$ref: "#/$defs/BroAbstract"
	}
];
var $defs = {
	BroItemList: {
		type: "object",
		description: "다중 타겟 문서 큐레이션을 위한 영속적 컨테이너 엔티티 (ItemList).",
		required: [
			"@context",
			"@type",
			"@id",
			"creator",
			"itemListElement",
			"dateCreated"
		],
		properties: {
			"@context": {
				"const": "https://schema.org"
			},
			"@type": {
				"const": "ItemList"
			},
			"@id": {
				$ref: "#/$defs/urnUuidOnly"
			},
			name: {
				type: "string",
				minLength: 2,
				maxLength: 2000,
				description: "리스트 컨테이너의 고유 명칭."
			},
			dateCreated: {
				$ref: "#/$defs/strictDateTime"
			},
			dateModified: {
				$ref: "#/$defs/strictDateTime",
				description: "버전 제어 및 동시성 관리를 위한 최종 수정 일시."
			},
			version: {
				type: [
					"string",
					"number"
				],
				description: "에그리거트 루트의 변경 이력 추적 및 낙관적 락(Optimistic Locking) 검증을 위한 버전 해시 또는 시퀀스 넘버."
			},
			creator: {
				type: "array",
				minItems: 1,
				uniqueItems: true,
				items: {
					$ref: "#/$defs/creatorRoot"
				}
			},
			itemListElement: {
				type: "array",
				description: "리스트에 포함된 개별 문서(Article 등)의 식별자 목록. 직접 내포(Embedding) 금지. 데이터 단편화 방지 및 URN 식별자 정규화를 위해 철저히 포인터 기반 참조로 격리함.",
				items: {
					type: "object",
					required: [
						"@id"
					],
					properties: {
						"@id": {
							$ref: "#/$defs/urnUuidOnly"
						}
					}
				}
			},
			inLanguage: {
				$ref: "#/$defs/languageArray"
			},
			keywords: {
				$ref: "#/$defs/keywordsArray"
			},
			additionalProperty: {
				$ref: "#/$defs/additionalPropertyArray"
			}
		}
	},
	BroArticle: {
		type: "object",
		description: "단일 파생 문서(Article) 처리를 위한 영속성 스키마. 기존 YAML 프론트매터 속성을 스키마 최상위 프로퍼티로 추출하여 검색 엔진 및 DB 인덱서의 직접 접근을 허용함.",
		required: [
			"@context",
			"@type",
			"@id",
			"about",
			"text",
			"creator",
			"dateCreated"
		],
		properties: {
			"@context": {
				"const": "https://schema.org"
			},
			"@type": {
				"const": "Article"
			},
			"@id": {
				$ref: "#/$defs/urnUuidOnly"
			},
			name: {
				type: "string",
				description: "파생 문서 자체의 제목. 시스템 반환 시 Article 엔티티의 최상위 명칭으로 사용됨."
			},
			aboutName: {
				type: "string",
				description: "현재 문서가 타겟팅(about)하고 있는 원본 코어 저작물의 텍스트 명칭(name). 원문 URN 참조가 실패하거나 지연 로딩될 경우의 디그레이드(Degrade) 처리를 위한 역정규화 데이터. 스키마 전역의 명명 규칙(Naming Convention) 통일성에 따라 Title 대신 Name을 접미사로 강제함."
			},
			aboutCreator: {
				type: "string",
				description: "현재 문서가 타겟팅하는 원본 코어 저작물의 원작자 텍스트 표기."
			},
			articleByline: {
				type: "string",
				description: "현재 파생 문서 작성자의 크레딧 라인 표기."
			},
			dateCreated: {
				$ref: "#/$defs/strictDateTime"
			},
			dateModified: {
				$ref: "#/$defs/strictDateTime"
			},
			datePublished: {
				$ref: "#/$defs/strictDateTime"
			},
			version: {
				type: [
					"string",
					"number"
				]
			},
			about: {
				type: "array",
				minItems: 1,
				uniqueItems: true,
				description: "파생 문서가 타겟팅하는 코어 저작물 엔티티의 식별자 묶음. 다중 판본 바인딩 시 복수 원소를 허용함.",
				items: {
					$ref: "#/$defs/terminalIdentifier"
				}
			},
			text: {
				$ref: "#/$defs/pureText"
			},
			inLanguage: {
				$ref: "#/$defs/languageArray"
			},
			keywords: {
				$ref: "#/$defs/keywordsArray"
			},
			image: {
				type: "array",
				items: {
					type: "string",
					format: "uri"
				},
				description: "관련 이미지 URL 배열."
			},
			citation: {
				type: "array",
				items: {
					type: "string",
					format: "uri"
				},
				description: "참고 문헌 또는 원문 URL 목록."
			},
			abstract: {
				type: "array",
				description: "현재 문서(Article)에 종속된 파생 요약본의 식별자(URN) 배열. 1:N 구조의 디스크 중복 적재를 막기 위한 식별자 참조. 본문 내포 절대 금지.",
				items: {
					type: "object",
					required: [
						"@id"
					],
					properties: {
						"@id": {
							$ref: "#/$defs/urnUuidOnly"
						}
					}
				}
			},
			creator: {
				type: "array",
				minItems: 1,
				uniqueItems: true,
				items: {
					$ref: "#/$defs/creatorRoot"
				}
			},
			additionalProperty: {
				$ref: "#/$defs/additionalPropertyArray"
			}
		}
	},
	BroAbstract: {
		type: "object",
		description: "구조화된 요약 데이터. isBasedOn 속성을 통해 원본 역참조.",
		required: [
			"@context",
			"@type",
			"@id",
			"text",
			"creator",
			"dateCreated",
			"isBasedOn"
		],
		properties: {
			"@context": {
				"const": "https://schema.org"
			},
			"@type": {
				"const": "CreativeWork"
			},
			"@id": {
				$ref: "#/$defs/urnUuidOnly"
			},
			name: {
				type: "string",
				description: "요약 데이터의 텍스트 명칭(제목). 스키마 전역의 식별 표제 단일화 정책에 따라 name 속성을 할당함."
			},
			dateCreated: {
				$ref: "#/$defs/strictDateTime"
			},
			dateModified: {
				$ref: "#/$defs/strictDateTime"
			},
			version: {
				type: [
					"string",
					"number"
				]
			},
			text: {
				$ref: "#/$defs/pureText"
			},
			inLanguage: {
				$ref: "#/$defs/languageArray"
			},
			keywords: {
				$ref: "#/$defs/keywordsArray"
			},
			image: {
				type: "array",
				items: {
					type: "string",
					format: "uri"
				},
				description: "관련 이미지 URL 배열."
			},
			citation: {
				type: "array",
				items: {
					type: "string",
					format: "uri"
				},
				description: "참고 문헌 또는 원문 URL 목록."
			},
			creator: {
				type: "array",
				minItems: 1,
				uniqueItems: true,
				items: {
					$ref: "#/$defs/creatorRoot"
				}
			},
			isBasedOn: {
				type: "array",
				minItems: 1,
				description: "이 요약이 기반하고 있는 원본 엔티티(Article 또는 도서 등 CreativeWork)의 단방향 외부 식별자 포인터.",
				items: {
					$ref: "#/$defs/terminalIdentifier"
				}
			},
			additionalProperty: {
				$ref: "#/$defs/additionalPropertyArray"
			}
		}
	},
	pureText: {
		type: "string",
		minLength: 0,
		maxLength: 300000,
		description: "순수 본문 문자열 (주로 Markdown 구조). YAML Frontmatter 캡슐화를 전면 폐기함. 인입 파이프라인에서 본 필드 내의 메타데이터 은닉을 감지할 경우 페이로드 수용을 거부(Reject)하며, 모든 메타 속성은 JSON의 1급 객체 또는 additionalProperty로 분리 추출되어야 함."
	},
	languageArray: {
		type: "array",
		items: {
			type: "string",
			pattern: "^[a-zA-Z]{2,3}(-[a-zA-Z0-9]+)?$"
		},
		description: "BCP 47 / ISO 639 언어 코드 목록."
	},
	keywordsArray: {
		type: "array",
		items: {
			type: "string"
		},
		description: "분류용 핵심어 목록."
	},
	additionalPropertyArray: {
		type: "array",
		description: "Schema.org 표준 PropertyValue 기반 동적 메타데이터 확장 컨테이너. 도서관이나 서비스별로 파편화된 커스텀 메타데이터(예: 평점, 완독 여부, 추천 연령 등)를 스키마를 오염시키지 않고 수용함. NoSQL이나 RDBMS의 JSON 컬럼에서 완벽한 기계적 인덱싱이 가능함.",
		items: {
			type: "object",
			required: [
				"@type",
				"name",
				"value"
			],
			properties: {
				"@type": {
					"const": "PropertyValue"
				},
				name: {
					type: "string",
					description: "동적 속성의 식별 키(Key)"
				},
				value: {
					description: "동적 속성의 값(Value). 원시 타입 및 객체 허용."
				}
			}
		}
	},
	urnIdentifier: {
		type: "string",
		description: "[BASE_PRIMITIVES: 원시 데이터 계층 식별자] 시스템 레벨의 소문자 URN Scheme 정규화를 전제로 한 정규식 집합.",
		oneOf: [
			{
				pattern: "^urn:isbn:(?:97[89]-?)?(?:\\d[ -]?){9}[\\dxX]$"
			},
			{
				pattern: "^urn:doi:10\\.\\d{4,9}\\/[-._;()/:A-Za-z0-9]+$"
			},
			{
				pattern: "^urn:uci:[a-zA-Z0-9]{3,10}[:\\-+][a-zA-Z0-9\\-+.:]+$"
			},
			{
				pattern: "^urn:kolis:[a-zA-Z0-9]+$"
			},
			{
				pattern: "^urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[457][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$"
			},
			{
				pattern: "^urn:nlk:[a-zA-Z0-9]+$"
			}
		]
	},
	urnUuidOnly: {
		type: "string",
		pattern: "^urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[457][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$",
		description: "UUID v4, v5, v7을 수용하는 정규화된 범용 고유 식별자 URN 포맷."
	},
	strictDateTime: {
		type: "string",
		format: "date-time",
		pattern: "^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(?:\\.[0-9]{1,6})?(?:Z|[+-][0-9]{2}:[0-9]{2})$",
		description: "RFC 3339 기반 타임스탬프 강제 규격. Z 또는 오프셋 명시를 누락한 경우 DB 데이터 오염으로 간주하여 인입을 차단함."
	},
	terminalIdentifier: {
		type: "object",
		description: "순환 참조(Billion Laughs 등) 무한 루프 렌더링 공격을 원천 차단하기 위해 계층 깊이를 제한한 터미널 식별 객체.",
		required: [
			"@type",
			"identifier"
		],
		properties: {
			"@type": {
				"enum": [
					"Article",
					"CreativeWork"
				]
			},
			identifier: {
				$ref: "#/$defs/urnIdentifier"
			}
		},
		additionalProperties: false
	},
	creatorRoot: {
		type: "object",
		description: "[CREATOR_ENTITIES] 작성자 엔티티 다형성 계층. 공공 및 법인은 @id 강제 검증, 개인은 수집 파편화 대응을 위한 선택적 @id 허용, 익명은 추적 불가능한 작성자 데이터의 유실 방지 Fallback.",
		required: [
			"@type"
		],
		oneOf: [
			{
				$ref: "#/$defs/creatorPerson"
			},
			{
				$ref: "#/$defs/creatorAnonymous"
			},
			{
				$ref: "#/$defs/creatorGovernment"
			},
			{
				$ref: "#/$defs/creatorCorporation"
			},
			{
				$ref: "#/$defs/creatorOrganization"
			},
			{
				$ref: "#/$defs/creatorSoftware"
			}
		]
	},
	creatorPerson: {
		type: "object",
		required: [
			"@type",
			"name"
		],
		properties: {
			"@type": {
				"const": "Person"
			},
			name: {
				type: "string",
				maxLength: 1000
			},
			"@id": {
				description: "인증된 사용자에 한해 부여되는 URN/ORCID 식별자. 파편화된 외부 데이터 스크래핑 인입 시 생략을 허용함.",
				oneOf: [
					{
						$ref: "#/$defs/urnUuidOnly"
					},
					{
						pattern: "^urn:orcid:\\d{4}-\\d{4}-\\d{4}-\\d{3}[0-9X]$"
					}
				]
			}
		},
		additionalProperties: false
	},
	creatorAnonymous: {
		type: "object",
		description: "네트워크 인입 단말 혹은 수집 파이프라인에서 작성자 엔티티 추적에 실패할 경우, null/undefined로 인한 스키마 크래시를 방지하는 Fallback 타입.",
		required: [
			"@type"
		],
		properties: {
			"@type": {
				"const": "Anonymous"
			},
			name: {
				type: "string",
				"default": "Anonymous",
				maxLength: 1000
			}
		},
		additionalProperties: false
	},
	creatorGovernment: {
		type: "object",
		required: [
			"@type",
			"@id",
			"name"
		],
		properties: {
			"@type": {
				"const": "GovernmentOrganization"
			},
			name: {
				type: "string",
				maxLength: 1000
			},
			"@id": {
				oneOf: [
					{
						$ref: "#/$defs/urnUuidOnly"
					},
					{
						pattern: "^urn:kr:govcode:\\d{7}$"
					}
				]
			}
		},
		additionalProperties: false
	},
	creatorCorporation: {
		type: "object",
		required: [
			"@type",
			"@id",
			"name"
		],
		properties: {
			"@type": {
				"const": "Corporation"
			},
			name: {
				type: "string",
				maxLength: 1000
			},
			"@id": {
				oneOf: [
					{
						$ref: "#/$defs/urnUuidOnly"
					},
					{
						pattern: "^urn:kr:crn:\\d{13}$"
					}
				]
			}
		},
		additionalProperties: false
	},
	creatorOrganization: {
		type: "object",
		required: [
			"@type",
			"@id",
			"name"
		],
		properties: {
			"@type": {
				"const": "Organization"
			},
			name: {
				type: "string",
				maxLength: 1000
			},
			"@id": {
				oneOf: [
					{
						$ref: "#/$defs/urnUuidOnly"
					},
					{
						pattern: "^urn:kr:npo:\\d{10}$"
					}
				]
			}
		},
		additionalProperties: false
	},
	creatorSoftware: {
		type: "object",
		required: [
			"@type",
			"@id",
			"name"
		],
		properties: {
			"@type": {
				"const": "SoftwareApplication"
			},
			name: {
				type: "string",
				maxLength: 1000
			},
			softwareVersion: {
				type: "string",
				maxLength: 50
			},
			"@id": {
				pattern: "^urn:model:[a-zA-Z0-9-]+:[a-zA-Z0-9\\.-]+$"
			}
		},
		additionalProperties: false
	}
};
var broV1Schema = {
	$schema: $schema,
	$id: $id,
	title: title,
	description: description,
	type: type,
	oneOf: oneOf,
	$defs: $defs
};

/**
 * URN Normalization Pipeline
 *
 * bro-v1-schema.json에서 (?i:) 플래그가 제거되었으므로,
 * Validation 이전 단계에서 식별자의 Scheme 부분을 소문자로 정규화합니다.
 *
 * 예: "URN:UUID:123..." → "urn:uuid:123..."
 *     "URN:ISBN:978..." → "urn:isbn:978..."
 */
/**
 * URN Scheme 부분만 소문자로 변환합니다.
 * 알려진 접두사를 대소문자 무시하여 매칭한 뒤, 접두사를 소문자로 정규화합니다.
 * NSS(Namespace Specific String) 부분은 원본 그대로 유지됩니다.
 *
 * 예: "URN:UUID:abc-def" → "urn:uuid:abc-def"
 *     "urn:model:Google:Gemini-1.5" → "urn:model:Google:Gemini-1.5" (NSS 보존)
 *     "URN:KR:CRN:1234567890123" → "urn:kr:crn:1234567890123"
 */
declare function normalizeUrnScheme(urn: string): string;
/**
 * 페이로드를 재귀적으로 순회하며 모든 URN 식별자의 Scheme을 소문자로 정규화합니다.
 * 원본 객체를 직접 수정(mutate)합니다.
 */
declare function normalizePayload<T>(payload: T): T;

/**
 * BRO v1.0 — 수동 작성 Discriminated Union 타입
 *
 * json-schema-to-typescript가 allOf + if/then discriminator 패턴을
 * 정확한 Union Type으로 변환하지 못하는 한계를 보완합니다.
 * 이 파일의 타입은 bro-v1-schema.json의 $defs와 1:1 동기화되어야 합니다.
 */
interface CreatorPerson {
    readonly "@type": "Person";
    readonly "@id"?: string;
    name: string;
}
interface CreatorAnonymous {
    readonly "@type": "Anonymous";
    name?: string;
}
interface CreatorGovernment {
    readonly "@type": "GovernmentOrganization";
    readonly "@id": string;
    name: string;
}
interface CreatorCorporation {
    readonly "@type": "Corporation";
    readonly "@id": string;
    name: string;
}
interface CreatorOrganization {
    readonly "@type": "Organization";
    readonly "@id": string;
    name: string;
}
interface CreatorSoftware {
    readonly "@type": "SoftwareApplication";
    readonly "@id": string;
    name: string;
    softwareVersion?: string;
}
/**
 * 6가지 작성자 타입의 Discriminated Union.
 * `@type` 필드를 discriminator로 사용합니다.
 */
type Creator = CreatorPerson | CreatorAnonymous | CreatorGovernment | CreatorCorporation | CreatorOrganization | CreatorSoftware;
/**
 * 지원하는 Creator @type 값들
 */
declare const CREATOR_TYPES: readonly ["Person", "Anonymous", "GovernmentOrganization", "Corporation", "Organization", "SoftwareApplication"];
type CreatorType = (typeof CREATOR_TYPES)[number];

/**
 * Validates data against the Bibliographic Reaction Object (BRO) schema.
 */
declare function validateBroSchema(data: unknown): {
    valid: boolean;
    errors: _cfworker_json_schema.OutputUnit[];
};

/**
 * BRO → BIBFRAME 2.0 변환기
 *
 * BRO 페이로드(Article/Abstract)를 BIBFRAME 2.0 JSON-LD 구조로 변환합니다.
 * Linked Open Data(LOD) 생태계와의 호환성을 위한 완전한 JSON-LD/BIBFRAME 2.0 변환을 지원합니다.
 *
 * [매핑 규칙]
 * - Article → bf:Work + bf:Review, 관계: bf:reviewOf
 * - CreativeWork (Abstract) → bf:Work + bf:Summary, 관계: bf:summaryOf
 * - Creator 다형성: Person/Anonymous → bf:Person, Organization 계열 → bf:Organization, Software → bf:Agent
 */

interface BibframeContribution {
    "@type": "bf:Contribution";
    "bf:agent": {
        "@type": string;
        "@id"?: string;
        "rdfs:label": string;
    };
}
interface BibframeIdentifier {
    "@type": "bf:Identifier";
    "rdf:value": string;
}
interface BibframeInstance {
    "@type": "bf:Instance";
    "bf:identifiedBy": BibframeIdentifier;
    "bf:title"?: {
        "@type": "bf:Title";
        "bf:mainTitle": string;
    };
    "bf:responsibilityStatement"?: string;
}
interface BibframeNote {
    "@type": "bf:Note";
    "rdfs:label": string;
}
interface BibframeWork {
    "@context": {
        bf: string;
        rdf: string;
        rdfs: string;
    };
    "@type": string[];
    "@id": string;
    "bf:originDate": string;
    "bf:changeDate"?: string;
    "bf:contribution": BibframeContribution[];
    "bf:title"?: {
        "@type": "bf:Title";
        "bf:mainTitle": string;
    };
    "bf:note": BibframeNote;
    [key: string]: unknown;
}
/**
 * BRO 페이로드에서 BIBFRAME 2.0으로의 변환.
 *
 * @param payload BroArticle 또는 BroAbstract 페이로드
 * @returns BIBFRAME 2.0 JSON-LD 객체
 *
 * @example
 * ```typescript
 * import { convertBroToBibframe } from '@slat.or.kr/bro-schema';
 *
 * const bibframe = convertBroToBibframe(articlePayload);
 * console.log(bibframe["@type"]); // ["bf:Work", "bf:Review"]
 * ```
 */
declare function convertBroToBibframe(payload: BroArticle | BroAbstract): BibframeWork;

/**
 * BRO → 마크다운+프론트매터 렌더러 (AI RAG 파이프라인용)
 *
 * BRO JSON 트리와 본문(text)을 합성하여 '마크다운+YAML 프론트매터' 형식의
 * 평문 텍스트를 On-the-fly로 렌더링합니다.
 *
 * LLM 컨텍스트 주입 시 JSON 구조보다 마크다운+프론트매터가
 * 토큰 효율 및 의미 파싱 정확도에서 유리하므로, 이 렌더러를 통해
 * RAG 검색 결과를 최적화된 형태로 변환합니다.
 *
 * [주의] 이 모듈은 YAML 의존성 없이 수동 직렬화를 수행합니다.
 */

type BroPayload = BroArticle | BroAbstract | BroItemList;
/**
 * BRO 페이로드를 마크다운+프론트매터 형식의 평문 텍스트로 렌더링합니다.
 * AI RAG 파이프라인에서 LLM 컨텍스트 주입용으로 사용합니다.
 *
 * @param payload BroArticle, BroAbstract, 또는 BroItemList 페이로드
 * @returns 마크다운+YAML 프론트매터 형식의 문자열
 *
 * @example
 * ```typescript
 * import { renderBroToMarkdown } from '@slat.or.kr/bro-schema';
 *
 * const markdown = renderBroToMarkdown(articlePayload);
 * // ---
 * // id: "urn:uuid:..."
 * // type: Article
 * // ...
 * // ---
 * // # 본문 내용
 * ```
 */
declare function renderBroToMarkdown(payload: BroPayload): string;

/**
 * KOMARC Subfield interface
 */
interface KomarcSubfield {
    code: string;
    value: string;
}
/**
 * KOMARC Data Field interface
 */
interface KomarcDataField {
    tag: string;
    indicator1: string;
    indicator2: string;
    subfields: KomarcSubfield[];
}
/**
 * KOMARC Control Field interface
 */
interface KomarcControlField {
    tag: string;
    value: string;
}
/**
 * Root KOMARC Record structure
 */
interface KomarcRecord {
    controlFields: KomarcControlField[];
    dataFields: KomarcDataField[];
}
/**
 * Converts a Bibliographic Reaction Object (BRO) to KOMARC format.
 * Supports Article, Abstract, and ItemList definition types.
 *
 * @param broPayload The BRO payload to convert
 * @returns A single KomarcRecord or an array of records
 */
declare function convertBroToKomarc(broPayload: BibliographicReactionObjectBROV10): KomarcRecord | KomarcRecord[];

export { type AdditionalPropertyArray, type BibframeContribution, type BibframeIdentifier, type BibframeInstance, type BibframeNote, type BibframeWork, type BibliographicReactionObjectBROV10, type BroAbstract, type BroArticle, type BroItemList, broV1Schema as BroV1Schema, CREATOR_TYPES, type Creator, type CreatorAnonymous, type CreatorCorporation, type CreatorGovernment, type CreatorOrganization, type CreatorPerson, type CreatorRoot, type CreatorSoftware, type CreatorType, type KeywordsArray, type KomarcControlField, type KomarcDataField, type KomarcRecord, type KomarcSubfield, type LanguageArray, type PureText, type StrictDateTime, type TerminalIdentifier, type UrnIdentifier, type UrnIdentifier1, type UrnUuidOnly, broV1Schema, convertBroToBibframe, convertBroToKomarc, normalizePayload, normalizeUrnScheme, renderBroToMarkdown, validateBroSchema };
