import * as _cfworker_json_schema from '@cfworker/json-schema';
import * as v from 'valibot';

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
/**
 * Bibliographic Reaction Object (BRO)의 원시스키마 BroItemList, BroArticle, BroAbstract. 본 스키마는 시스템 쓰기(Write/Command) 전용 모델이며, 클라이언트 조회를 위한 내포(Embedding) 트리 변환은 미들웨어 계층의 책임으로 위임함.
 * [ARCHITECTURE CORE DIRECTIVE] 본 원시 스키마는 애그리거트 루트(Aggregate Root) 간의 객체 내포(Embedding)를 엄격히 금지하고 단방향 URN 식별자(@id) 참조만을 허용한다. 이는 분산 DB 환경에서 트랜잭션 락 경합과 다중 판본 업데이트 이상을 방어하기 위한 CQRS 쓰기 파이프라인의 물리적 제약이다. 프론트엔드 렌더링 최적화를 위한 JSON 내포 구조(View Model)가 필요할 경우, 본 원시 스키마를 수정하지 말고 도메인 계층에서 In-Memory Join을 수행하여 도메인 특화 응답 DTO를 합성할 것.
 */
type BibliographicReactionObjectBRO = BroItemList | BroArticle | BroAbstract;
/**
 * UUID v4(랜덤) 및 v7(타임스탬프) v5(네임스페이스 기반 SHA-1 해시)
 */
type UrnUuidOnly = string;
/**
 * [CREATOR_ENTITIES: 2. 저자 엔티티 계층] 다형성 속성 출혈(Property Bleeding) 상호 배제.
 */
type CreatorRoot = CreatorPerson$1 | CreatorGovernment$1 | CreatorCorporation$1 | CreatorOrganization$1 | CreatorSoftware$1;
type UrnOrcid = string;
type UrnIsni = string;
type UrnGovcode = string;
type UrnLei = string;
type UrnCrn = string;
type UrnBrn = string;
type UrnNpo = string;
type UrnModel = string;
/**
 * RFC 3339 기반 날짜 포맷 검증. Z 또는 오프셋(+09:00)을 강제하여 타임존 누락으로 인한 DB 데이터 오염 방지.
 */
type StrictDateTime = string;
type UrnIdentifier = {
    [k: string]: unknown;
} | {
    [k: string]: unknown;
} | {
    [k: string]: unknown;
} | {
    [k: string]: unknown;
} | {
    [k: string]: unknown;
} | {
    [k: string]: unknown;
};
type UrnIdentifier1 = string;
/**
 * 범용 문서 텍스트. 최상단 YAML Frontmatter 캡슐화 필수. 데이터 인입 시 프론트매터 내부의 임의의 키(Arbitrary Keys) 확장은 전면 허용됨. 단, API 반환 및 영속화 객체 표출 시 파이프라인은 반드시 데이터를 정규화하여 1급 필드인 `title`(string), `byline`(string[]), `language`(string[]), `keywords`(string[]), `image`(string[]), `source_url`(string[])만을 최상위 노드에 직렬화하고, 기타 모든 잔여 동적 데이터는 `others: [{key: value}, ...]` 형태의 배열 객체로 강제 묶음 처리하여 마크다운을 재조립해야 함. [SYSTEM_CONSTRAINT: 2-Pass Validation Required]
 */
type BoundedText = string;
/**
 * 다중 타겟 문서 큐레이션을 위한 영속적 컨테이너 엔티티 (ItemList).
 */
interface BroItemList {
    "@context": "https://schema.org";
    "@type": "ItemList";
    "@id"?: UrnUuidOnly;
    name?: string;
    /**
     * @minItems 1
     */
    creator: [CreatorRoot, ...CreatorRoot[]];
    /**
     * 리스트에 포함된 개별 문서(Article 등)의 식별자 목록. 페이로드 생성 시 반드시 @id 객체 배열만을 전송해야 하며, 문서 객체 전체를 배열 내부에 내포(Embed)하는 페이로드는 검증(Validation) 단계에서 거부(Reject)된다.
     * [ANTI-PATTERN PREVENTION] itemListElement 내부의 oneOf를 통한 Article 객체 직접 포함 허용 로직은 데이터 단편화 방지 및 식별자 정규화를 위해 영구 삭제됨. 모든 하위 엔티티 결합은 오직 @id 포인터로만 이루어져야 함.
     */
    itemListElement: {
        "@id": UrnUuidOnly;
        [k: string]: unknown;
    }[];
    [k: string]: unknown;
}
interface CreatorPerson$1 {
    "@type": "Person";
    name: string;
    "@id": UrnUuidOnly | UrnOrcid | UrnIsni;
}
interface CreatorGovernment$1 {
    "@type": "GovernmentOrganization";
    name: string;
    "@id": UrnUuidOnly | UrnGovcode | UrnLei | UrnIsni;
}
interface CreatorCorporation$1 {
    "@type": "Corporation";
    name: string;
    "@id": UrnUuidOnly | UrnCrn | UrnBrn | UrnLei | UrnIsni;
}
interface CreatorOrganization$1 {
    "@type": "Organization";
    name: string;
    "@id": UrnUuidOnly | UrnNpo | UrnLei | UrnIsni;
}
interface CreatorSoftware$1 {
    "@type": "SoftwareApplication";
    name: string;
    softwareVersion?: string;
    "@id": UrnModel;
}
/**
 * 단일 코어 문서(Article) 처리를 위한 쓰기/영속성 스키마. 파생 문서(Abstract 등)와의 결합은 외부 참조(@id)로만 이뤄진다.
 */
interface BroArticle {
    "@context": "https://schema.org";
    "@type": "Article";
    "@id"?: UrnUuidOnly;
    dateCreated: StrictDateTime;
    datePublished?: StrictDateTime;
    /**
     * 파생 문서가 타겟팅하는 코어 저작물 엔티티. 다중 판본 바인딩 시 복수의 원소를 허용하나, 각 요소는 단일 URN을 소유함.
     *
     * @minItems 1
     */
    about: [TerminalIdentifier, ...TerminalIdentifier[]];
    text: BoundedText;
    /**
     * 현재 문서(Article)에 종속된 파생 요약본의 식별자(URN) 배열. 요약본의 상세 텍스트(Text)는 포함하지 않는다.
     * [DATA REDUNDANCY LOCK] Article 페이로드 내에 Abstract 본문 내포를 허용할 경우 발생하는 1:N 구조의 디스크 중복 적재(Redundancy) 및 B-Tree 분할을 막기 위해 철저히 식별자 참조 체계로 고립시킴.
     */
    abstract?: {
        "@id": UrnUuidOnly;
        [k: string]: unknown;
    }[];
    /**
     * @minItems 1
     */
    creator: [CreatorRoot, ...CreatorRoot[]];
    [k: string]: unknown;
}
/**
 * 순환 참조(Billion Laughs) 공격을 차단하기 위한 터미널 객체.
 */
interface TerminalIdentifier {
    "@type": "Article" | "CreativeWork";
    /**
     * [BASE_PRIMITIVES: 1. 원시 데이터 계층 - 식별자, 날짜 통제] 식별자 검증. 시스템 레벨의 소문자 URN Scheme 정규화를 전제로 패턴을 단순화함.
     */
    identifier: UrnIdentifier & UrnIdentifier1;
}
/**
 * 단일 요약본(Abstract) 처리를 위한 원시 스키마
 */
interface BroAbstract {
    "@context": "https://schema.org";
    "@type": "CreativeWork";
    "@id"?: UrnUuidOnly;
    dateCreated: StrictDateTime;
    datePublished?: StrictDateTime;
    text: BoundedText;
    /**
     * @minItems 1
     */
    creator: [CreatorRoot, ...CreatorRoot[]];
    /**
     * 이 요약이 기반하고 있는 원본 엔티티(Article 또는 도서 등 CreativeWork)의 식별자
     *
     * @minItems 1
     */
    isBasedOn: [TerminalIdentifier, ...TerminalIdentifier[]];
    [k: string]: unknown;
}

var $schema = "https://json-schema.org/draft/2020-12/schema";
var $id = "https://schema.slat.or.kr/bro/v1/schema.json";
var title = "Bibliographic Reaction Object (BRO)";
var description = "Bibliographic Reaction Object (BRO)의 원시스키마 BroItemList, BroArticle, BroAbstract. 본 스키마는 시스템 쓰기(Write/Command) 전용 모델이며, 클라이언트 조회를 위한 내포(Embedding) 트리 변환은 미들웨어 계층의 책임으로 위임함.\n[ARCHITECTURE CORE DIRECTIVE] 본 원시 스키마는 애그리거트 루트(Aggregate Root) 간의 객체 내포(Embedding)를 엄격히 금지하고 단방향 URN 식별자(@id) 참조만을 허용한다. 이는 분산 DB 환경에서 트랜잭션 락 경합과 다중 판본 업데이트 이상을 방어하기 위한 CQRS 쓰기 파이프라인의 물리적 제약이다. 프론트엔드 렌더링 최적화를 위한 JSON 내포 구조(View Model)가 필요할 경우, 본 원시 스키마를 수정하지 말고 도메인 계층에서 In-Memory Join을 수행하여 도메인 특화 응답 DTO를 합성할 것.";
var type = "object";
var oneOf = [
	{
		$ref: "#/$defs/BroItemList"
	},
	{
		$ref: "#/$defs/BroArticle"
	},
	{
		$ref: "#/$defs/BroAbstract"
	}
];
var $defs = {
	BroItemList: {
		type: "object",
		description: "다중 타겟 문서 큐레이션을 위한 영속적 컨테이너 엔티티 (ItemList).",
		required: [
			"@context",
			"@type",
			"creator",
			"itemListElement"
		],
		properties: {
			"@context": {
				"const": "https://schema.org"
			},
			"@type": {
				"const": "ItemList"
			},
			"@id": {
				$ref: "#/$defs/urnUuidOnly"
			},
			name: {
				type: "string",
				minLength: 2,
				maxLength: 2000
			},
			creator: {
				type: "array",
				minItems: 1,
				uniqueItems: true,
				items: {
					$ref: "#/$defs/creatorRoot"
				}
			},
			itemListElement: {
				type: "array",
				description: "리스트에 포함된 개별 문서(Article 등)의 식별자 목록. 페이로드 생성 시 반드시 @id 객체 배열만을 전송해야 하며, 문서 객체 전체를 배열 내부에 내포(Embed)하는 페이로드는 검증(Validation) 단계에서 거부(Reject)된다.\n[ANTI-PATTERN PREVENTION] itemListElement 내부의 oneOf를 통한 Article 객체 직접 포함 허용 로직은 데이터 단편화 방지 및 식별자 정규화를 위해 영구 삭제됨. 모든 하위 엔티티 결합은 오직 @id 포인터로만 이루어져야 함.",
				items: {
					type: "object",
					required: [
						"@id"
					],
					properties: {
						"@id": {
							$ref: "#/$defs/urnUuidOnly"
						}
					}
				}
			}
		}
	},
	BroArticle: {
		type: "object",
		description: "단일 코어 문서(Article) 처리를 위한 쓰기/영속성 스키마. 파생 문서(Abstract 등)와의 결합은 외부 참조(@id)로만 이뤄진다.",
		required: [
			"@context",
			"@type",
			"about",
			"text",
			"creator",
			"dateCreated"
		],
		properties: {
			"@context": {
				"const": "https://schema.org"
			},
			"@type": {
				"const": "Article"
			},
			"@id": {
				$ref: "#/$defs/urnUuidOnly"
			},
			dateCreated: {
				$ref: "#/$defs/strictDateTime"
			},
			datePublished: {
				$ref: "#/$defs/strictDateTime"
			},
			about: {
				type: "array",
				minItems: 1,
				uniqueItems: true,
				description: "파생 문서가 타겟팅하는 코어 저작물 엔티티. 다중 판본 바인딩 시 복수의 원소를 허용하나, 각 요소는 단일 URN을 소유함.",
				items: {
					$ref: "#/$defs/terminalIdentifier"
				}
			},
			text: {
				$ref: "#/$defs/boundedText"
			},
			abstract: {
				type: "array",
				description: "현재 문서(Article)에 종속된 파생 요약본의 식별자(URN) 배열. 요약본의 상세 텍스트(Text)는 포함하지 않는다.\n[DATA REDUNDANCY LOCK] Article 페이로드 내에 Abstract 본문 내포를 허용할 경우 발생하는 1:N 구조의 디스크 중복 적재(Redundancy) 및 B-Tree 분할을 막기 위해 철저히 식별자 참조 체계로 고립시킴.",
				items: {
					type: "object",
					required: [
						"@id"
					],
					properties: {
						"@id": {
							$ref: "#/$defs/urnUuidOnly"
						}
					}
				}
			},
			creator: {
				type: "array",
				minItems: 1,
				uniqueItems: true,
				items: {
					$ref: "#/$defs/creatorRoot"
				}
			}
		}
	},
	BroAbstract: {
		type: "object",
		description: "단일 요약본(Abstract) 처리를 위한 원시 스키마",
		required: [
			"@context",
			"@type",
			"text",
			"creator",
			"dateCreated",
			"isBasedOn"
		],
		properties: {
			"@context": {
				"const": "https://schema.org"
			},
			"@type": {
				"const": "CreativeWork"
			},
			"@id": {
				$ref: "#/$defs/urnUuidOnly"
			},
			dateCreated: {
				$ref: "#/$defs/strictDateTime"
			},
			datePublished: {
				$ref: "#/$defs/strictDateTime"
			},
			text: {
				$ref: "#/$defs/boundedText"
			},
			creator: {
				type: "array",
				minItems: 1,
				uniqueItems: true,
				items: {
					$ref: "#/$defs/creatorRoot"
				}
			},
			isBasedOn: {
				type: "array",
				minItems: 1,
				description: "이 요약이 기반하고 있는 원본 엔티티(Article 또는 도서 등 CreativeWork)의 식별자",
				items: {
					$ref: "#/$defs/terminalIdentifier"
				}
			}
		}
	},
	urnIdentifier: {
		type: "string",
		description: "[BASE_PRIMITIVES: 1. 원시 데이터 계층 - 식별자, 날짜 통제] 식별자 검증. 시스템 레벨의 소문자 URN Scheme 정규화를 전제로 패턴을 단순화함.",
		oneOf: [
			{
				pattern: "^urn:isbn:(?:97[89]-?)?(?:\\d[ -]?){9}[\\dxX]$"
			},
			{
				pattern: "^urn:doi:10\\.\\d{4,9}\\/[-._;()/:A-Za-z0-9]+$"
			},
			{
				pattern: "^urn:uci:[a-zA-Z0-9]{3,10}[:\\-+][a-zA-Z0-9\\-+.:]+$"
			},
			{
				pattern: "^urn:kolis:[a-zA-Z0-9]+$"
			},
			{
				pattern: "^urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[457][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$"
			},
			{
				pattern: "^urn:nlk:[a-zA-Z0-9]+$"
			}
		]
	},
	urnUuidOnly: {
		type: "string",
		pattern: "^urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[457][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$",
		description: "UUID v4(랜덤) 및 v7(타임스탬프) v5(네임스페이스 기반 SHA-1 해시)"
	},
	urnOrcid: {
		type: "string",
		pattern: "^urn:orcid:\\d{4}-\\d{4}-\\d{4}-\\d{3}[0-9X]$"
	},
	urnIsni: {
		type: "string",
		pattern: "^urn:isni:0000[ \\-]?\\d{4}[ \\-]?\\d{4}[ \\-]?\\d{3}[0-9X]$"
	},
	urnLei: {
		type: "string",
		pattern: "^urn:lei:[0-9A-Z]{20}$"
	},
	urnGovcode: {
		type: "string",
		pattern: "^urn:kr:govcode:\\d{7}$"
	},
	urnCrn: {
		type: "string",
		pattern: "^urn:kr:crn:\\d{13}$"
	},
	urnBrn: {
		type: "string",
		pattern: "^urn:kr:brn:\\d{10}$"
	},
	urnNpo: {
		type: "string",
		pattern: "^urn:kr:npo:\\d{10}$"
	},
	urnModel: {
		type: "string",
		pattern: "^urn:model:[a-zA-Z0-9-]+:[a-zA-Z0-9\\.-]+$"
	},
	strictDateTime: {
		type: "string",
		format: "date-time",
		pattern: "^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(?:\\.[0-9]{1,6})?(?:Z|[+-][0-9]{2}:[0-9]{2})$",
		description: "RFC 3339 기반 날짜 포맷 검증. Z 또는 오프셋(+09:00)을 강제하여 타임존 누락으로 인한 DB 데이터 오염 방지."
	},
	boundedText: {
		type: "string",
		minLength: 0,
		maxLength: 300000,
		description: "범용 문서 텍스트. 최상단 YAML Frontmatter 캡슐화 필수. 데이터 인입 시 프론트매터 내부의 임의의 키(Arbitrary Keys) 확장은 전면 허용됨. 단, API 반환 및 영속화 객체 표출 시 파이프라인은 반드시 데이터를 정규화하여 1급 필드인 `title`(string), `byline`(string[]), `language`(string[]), `keywords`(string[]), `image`(string[]), `source_url`(string[])만을 최상위 노드에 직렬화하고, 기타 모든 잔여 동적 데이터는 `others: [{key: value}, ...]` 형태의 배열 객체로 강제 묶음 처리하여 마크다운을 재조립해야 함. [SYSTEM_CONSTRAINT: 2-Pass Validation Required]",
		"x-frontmatter-schema": {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				title: {
					type: "string"
				},
				byline: {
					type: "array",
					items: {
						type: "string"
					}
				},
				language: {
					type: "array",
					items: {
						type: "string",
						pattern: "^[a-zA-Z]{2,3}(-[a-zA-Z0-9]+)?$"
					},
					minItems: 1,
					uniqueItems: true
				},
				keywords: {
					type: "array",
					items: {
						type: "string"
					}
				},
				image: {
					type: "array",
					items: {
						type: "string"
					}
				},
				source_url: {
					type: "array",
					items: {
						type: "string"
					}
				},
				others: {
					type: "array",
					items: {
						type: "object",
						additionalProperties: true
					}
				}
			},
			additionalProperties: false,
			required: [
			]
		}
	},
	terminalIdentifier: {
		type: "object",
		description: "순환 참조(Billion Laughs) 공격을 차단하기 위한 터미널 객체.",
		required: [
			"@type",
			"identifier"
		],
		properties: {
			"@type": {
				"enum": [
					"Article",
					"CreativeWork"
				]
			},
			identifier: {
				$ref: "#/$defs/urnIdentifier"
			}
		},
		additionalProperties: false
	},
	creatorRoot: {
		type: "object",
		description: "[CREATOR_ENTITIES: 2. 저자 엔티티 계층] 다형성 속성 출혈(Property Bleeding) 상호 배제.",
		required: [
			"@type"
		],
		oneOf: [
			{
				$ref: "#/$defs/creatorPerson"
			},
			{
				$ref: "#/$defs/creatorGovernment"
			},
			{
				$ref: "#/$defs/creatorCorporation"
			},
			{
				$ref: "#/$defs/creatorOrganization"
			},
			{
				$ref: "#/$defs/creatorSoftware"
			}
		]
	},
	creatorPerson: {
		type: "object",
		required: [
			"@type",
			"@id",
			"name"
		],
		properties: {
			"@type": {
				"const": "Person"
			},
			name: {
				type: "string",
				maxLength: 1000
			},
			"@id": {
				oneOf: [
					{
						$ref: "#/$defs/urnUuidOnly"
					},
					{
						$ref: "#/$defs/urnOrcid"
					},
					{
						$ref: "#/$defs/urnIsni"
					}
				]
			}
		},
		additionalProperties: false
	},
	creatorGovernment: {
		type: "object",
		required: [
			"@type",
			"@id",
			"name"
		],
		properties: {
			"@type": {
				"const": "GovernmentOrganization"
			},
			name: {
				type: "string",
				maxLength: 1000
			},
			"@id": {
				oneOf: [
					{
						$ref: "#/$defs/urnUuidOnly"
					},
					{
						$ref: "#/$defs/urnGovcode"
					},
					{
						$ref: "#/$defs/urnLei"
					},
					{
						$ref: "#/$defs/urnIsni"
					}
				]
			}
		},
		additionalProperties: false
	},
	creatorCorporation: {
		type: "object",
		required: [
			"@type",
			"@id",
			"name"
		],
		properties: {
			"@type": {
				"const": "Corporation"
			},
			name: {
				type: "string",
				maxLength: 1000
			},
			"@id": {
				oneOf: [
					{
						$ref: "#/$defs/urnUuidOnly"
					},
					{
						$ref: "#/$defs/urnCrn"
					},
					{
						$ref: "#/$defs/urnBrn"
					},
					{
						$ref: "#/$defs/urnLei"
					},
					{
						$ref: "#/$defs/urnIsni"
					}
				]
			}
		},
		additionalProperties: false
	},
	creatorOrganization: {
		type: "object",
		required: [
			"@type",
			"@id",
			"name"
		],
		properties: {
			"@type": {
				"const": "Organization"
			},
			name: {
				type: "string",
				maxLength: 1000
			},
			"@id": {
				oneOf: [
					{
						$ref: "#/$defs/urnUuidOnly"
					},
					{
						$ref: "#/$defs/urnNpo"
					},
					{
						$ref: "#/$defs/urnLei"
					},
					{
						$ref: "#/$defs/urnIsni"
					}
				]
			}
		},
		additionalProperties: false
	},
	creatorSoftware: {
		type: "object",
		required: [
			"@type",
			"@id",
			"name"
		],
		properties: {
			"@type": {
				"const": "SoftwareApplication"
			},
			name: {
				type: "string",
				maxLength: 1000
			},
			softwareVersion: {
				type: "string",
				maxLength: 50
			},
			"@id": {
				oneOf: [
					{
						$ref: "#/$defs/urnModel"
					}
				]
			}
		},
		additionalProperties: false
	}
};
var broV1Schema = {
	$schema: $schema,
	$id: $id,
	title: title,
	description: description,
	type: type,
	oneOf: oneOf,
	$defs: $defs
};

declare const StrictFrontmatterSchema: v.StrictObjectSchema<{
    readonly title: v.OptionalSchema<v.StringSchema<"Title must be a string.">, undefined>;
    readonly language: v.OptionalSchema<v.ArraySchema<v.SchemaWithPipe<readonly [v.StringSchema<"Language items must be strings.">, v.RegexAction<string, "Must be a valid BCP 47 / ISO 639 language code.">]>, "Language must be an array of BCP 47 codes.">, undefined>;
    readonly keywords: v.OptionalSchema<v.ArraySchema<v.StringSchema<"Keywords must be an array of strings.">, undefined>, undefined>;
    readonly byline: v.OptionalSchema<v.ArraySchema<v.StringSchema<"Byline must be an array of strings.">, undefined>, undefined>;
    readonly image: v.OptionalSchema<v.ArraySchema<v.StringSchema<"Image must be an array of strings.">, undefined>, undefined>;
    readonly source_url: v.OptionalSchema<v.ArraySchema<v.StringSchema<"Source URL must be an array of strings.">, undefined>, undefined>;
    readonly others: v.OptionalSchema<v.ArraySchema<v.RecordSchema<v.StringSchema<undefined>, v.AnySchema, undefined>, "Others must be an array of {key: value} objects.">, undefined>;
}, undefined>;
declare const DynamicFieldSchema: v.RecordSchema<v.StringSchema<undefined>, v.AnySchema, undefined>;
type StrictFrontmatter = v.InferOutput<typeof StrictFrontmatterSchema>;
type DynamicField = v.InferOutput<typeof DynamicFieldSchema>;
interface FrontmatterResult {
    data: StrictFrontmatter;
    others: DynamicField[];
    content: string;
}

/**
 * URN Normalization Pipeline
 *
 * bro-v1-schema.json에서 (?i:) 플래그가 제거되었으므로,
 * Validation 이전 단계에서 식별자의 Scheme 부분을 소문자로 정규화합니다.
 *
 * 예: "URN:UUID:123..." → "urn:uuid:123..."
 *     "URN:ISBN:978..." → "urn:isbn:978..."
 */
/**
 * URN Scheme 부분만 소문자로 변환합니다.
 * 알려진 접두사를 대소문자 무시하여 매칭한 뒤, 접두사를 소문자로 정규화합니다.
 * NSS(Namespace Specific String) 부분은 원본 그대로 유지됩니다.
 *
 * 예: "URN:UUID:abc-def" → "urn:uuid:abc-def"
 *     "urn:model:Google:Gemini-1.5" → "urn:model:Google:Gemini-1.5" (NSS 보존)
 *     "URN:KR:CRN:1234567890123" → "urn:kr:crn:1234567890123"
 */
declare function normalizeUrnScheme(urn: string): string;
/**
 * 페이로드를 재귀적으로 순회하며 모든 URN 식별자의 Scheme을 소문자로 정규화합니다.
 * 원본 객체를 직접 수정(mutate)합니다.
 */
declare function normalizePayload<T>(payload: T): T;

/**
 * BRO v1 — 수동 작성 Discriminated Union 타입
 *
 * json-schema-to-typescript가 allOf + if/then discriminator 패턴을
 * 정확한 Union Type으로 변환하지 못하는 한계를 보완합니다.
 * 이 파일의 타입은 bro-v1-schema.json의 $defs와 1:1 동기화되어야 합니다.
 */
interface CreatorPerson {
    readonly "@type": "Person";
    readonly "@id": string;
    name: string;
}
interface CreatorGovernment {
    readonly "@type": "GovernmentOrganization";
    readonly "@id": string;
    name: string;
}
interface CreatorCorporation {
    readonly "@type": "Corporation";
    readonly "@id": string;
    name: string;
}
interface CreatorOrganization {
    readonly "@type": "Organization";
    readonly "@id": string;
    name: string;
}
interface CreatorSoftware {
    readonly "@type": "SoftwareApplication";
    readonly "@id": string;
    name: string;
    softwareVersion?: string;
}
/**
 * 5가지 작성자 타입의 Discriminated Union.
 * `@type` 필드를 discriminator로 사용합니다.
 */
type Creator = CreatorPerson | CreatorGovernment | CreatorCorporation | CreatorOrganization | CreatorSoftware;
/**
 * 지원하는 Creator @type 값들
 */
declare const CREATOR_TYPES: readonly ["Person", "GovernmentOrganization", "Corporation", "Organization", "SoftwareApplication"];
type CreatorType = (typeof CREATOR_TYPES)[number];

/**
 * Validates data against the Book Article List Ontology (BRO) schema.
 */
declare function validateBroSchema(data: unknown): {
    valid: boolean;
    errors: _cfworker_json_schema.OutputUnit[];
};

/**
 * Parses frontmatter and body content.
 * Supports both full markdown strings and separated sections (yaml + body).
 *
 * [보안] Single arg 모드에서는 최상단 5,000자 이내에서만 Frontmatter를 탐색합니다.
 */
declare function parseFrontmatter(markdownOrYaml: string, body?: string): FrontmatterResult;
/**
 * Serializes the strictly separated data back into a Markdown document.
 */
declare function serializeFrontmatter(data: StrictFrontmatter, others: DynamicField[], content: string): string;

/**
 * KOMARC Subfield interface
 */
interface KomarcSubfield {
    code: string;
    value: string;
}
/**
 * KOMARC Data Field interface
 */
interface KomarcDataField {
    tag: string;
    indicator1: string;
    indicator2: string;
    subfields: KomarcSubfield[];
}
/**
 * KOMARC Control Field interface
 */
interface KomarcControlField {
    tag: string;
    value: string;
}
/**
 * Root KOMARC Record structure
 */
interface KomarcRecord {
    controlFields: KomarcControlField[];
    dataFields: KomarcDataField[];
}
/**
 * Converts a Bibliographic Reaction Object (BRO) to KOMARC format.
 * Supports Article, Abstract, and ItemList definition types.
 *
 * @param broPayload The BRO payload to convert
 * @returns A single KomarcRecord or an array of records
 */
declare function convertBroToKomarc(broPayload: BibliographicReactionObjectBRO): KomarcRecord | KomarcRecord[];

export { type BibliographicReactionObjectBRO, type BoundedText, type BroAbstract, type BroArticle, type BroItemList, broV1Schema as BroV1Schema, CREATOR_TYPES, type Creator, type CreatorCorporation, type CreatorGovernment, type CreatorOrganization, type CreatorPerson, type CreatorRoot, type CreatorSoftware, type CreatorType, type KomarcControlField, type KomarcDataField, type KomarcRecord, type KomarcSubfield, type StrictDateTime, type TerminalIdentifier, type UrnBrn, type UrnCrn, type UrnGovcode, type UrnIdentifier, type UrnIdentifier1, type UrnIsni, type UrnLei, type UrnModel, type UrnNpo, type UrnOrcid, type UrnUuidOnly, broV1Schema, convertBroToKomarc, normalizePayload, normalizeUrnScheme, parseFrontmatter, serializeFrontmatter, validateBroSchema };
