// This file is auto-generated. Do not edit it manually.
// To update these types, run `pnpm run generate-types`

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Bibliographic Reaction Object (BRO)의 원시스키마 BroItemList, BroArticle, BroAbstract. 본 스키마는 시스템 쓰기(Write/Command) 전용 모델이며, 클라이언트 조회를 위한 내포(Embedding) 트리 변환은 미들웨어 계층의 책임으로 위임함.
 */
export type BibliographicReactionObjectBRO = BroItemList | BroArticle | BroAbstract;
/**
 * UUID v4(랜덤) 및 v7(타임스탬프) v5(네임스페이스 기반 SHA-1 해시)
 */
export type UrnUuidOnly = string;
export type AuthorRoot = {
  [k: string]: unknown;
} & {
  [k: string]: unknown;
} & {
  [k: string]: unknown;
} & {
  [k: string]: unknown;
} & {
  [k: string]: unknown;
};
/**
 * RFC 3339 기반 날짜 포맷 검증. Z 또는 오프셋(+09:00)을 강제하여 타임존 누락으로 인한 DB 데이터 오염 방지.
 */
export type StrictDateTime = string;
export type UrnIdentifier =
  | {
      [k: string]: unknown;
    }
  | {
      [k: string]: unknown;
    }
  | {
      [k: string]: unknown;
    }
  | {
      [k: string]: unknown;
    }
  | {
      [k: string]: unknown;
    }
  | {
      [k: string]: unknown;
    };
export type UrnIdentifier1 = string;
/**
 * 범용 문서 텍스트. 최상단 YAML Frontmatter 캡슐화 필수. 데이터 인입 시 프론트매터 내부의 임의의 키(Arbitrary Keys) 확장은 전면 허용됨. 단, API 반환 및 영속화 객체 표출 시 파이프라인은 반드시 데이터를 정규화하여 1급 필드인 `title`(string), `byline`(string[]), `language`(string[]), `keywords`(string[]), `image`(string[]), `source_url`(string[])만을 최상위 노드에 직렬화하고, 기타 모든 잔여 동적 데이터는 `others: [{key: value}, ...]` 형태의 배열 객체로 강제 묶음 처리하여 마크다운을 재조립해야 함. [SYSTEM_CONSTRAINT: 2-Pass Validation Required]
 */
export type BoundedText = string;

/**
 * 다중 타겟 문서 큐레이션을 위한 영속적 컨테이너 엔티티 (ItemList).
 */
export interface BroItemList {
  "@context": "https://schema.org";
  "@type": "ItemList";
  "@id"?: UrnUuidOnly;
  name?: string;
  /**
   * @minItems 1
   */
  author: [AuthorRoot, ...AuthorRoot[]];
  /**
   * 리스트에 포함된 개별 문서(Article 등)의 식별자 목록. 페이로드 생성 시 반드시 @id 객체 배열만을 전송해야 하며, 문서 객체 전체를 배열 내부에 내포(Embed)하는 페이로드는 검증(Validation) 단계에서 거부(Reject)된다.
   *
   * @minItems 0
   */
  itemListElement: {
    "@id": UrnUuidOnly;
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
/**
 * 단일 코어 문서(Article) 처리를 위한 쓰기/영속성 스키마. 파생 문서(Abstract 등)와의 결합은 외부 참조(@id)로만 이뤄진다.
 */
export interface BroArticle {
  "@context": "https://schema.org";
  "@type": "Article";
  "@id"?: UrnUuidOnly;
  dateCreated: StrictDateTime;
  datePublished?: StrictDateTime;
  /**
   * 파생 문서가 타겟팅하는 코어 저작물 엔티티. 다중 판본 바인딩 시 복수의 원소를 허용하나, 각 요소는 단일 URN을 소유함.
   *
   * @minItems 1
   */
  about: [TerminalIdentifier, ...TerminalIdentifier[]];
  text: BoundedText;
  /**
   * 현재 문서(Article)에 종속된 파생 요약본의 식별자(URN) 배열. 요약본의 상세 텍스트(Text)는 포함하지 않는다.
   */
  abstract?: {
    "@id": UrnUuidOnly;
    [k: string]: unknown;
  }[];
  /**
   * @minItems 1
   */
  author: [AuthorRoot, ...AuthorRoot[]];
  [k: string]: unknown;
}
/**
 * 순환 참조(Billion Laughs) 공격을 차단하기 위한 터미널 객체.
 */
export interface TerminalIdentifier {
  "@type": "Article" | "CreativeWork";
  /**
   * 식별자 검증. 시스템 레벨의 소문자 URN Scheme 정규화를 전제로 패턴을 단순화함.
   */
  identifier: UrnIdentifier & UrnIdentifier1;
}
/**
 * 단일 요약본(Abstract) 처리를 위한 원시 스키마
 */
export interface BroAbstract {
  "@context": "https://schema.org";
  "@type": "CreativeWork";
  "@id"?: UrnUuidOnly;
  dateCreated: StrictDateTime;
  datePublished?: StrictDateTime;
  text: BoundedText;
  /**
   * 요약본의 언어 코드 (예: ko, en)
   */
  inLanguage?: string;
  /**
   * @minItems 1
   */
  author: [AuthorRoot, ...AuthorRoot[]];
  /**
   * 이 요약이 기반하고 있는 원본 엔티티(Article 또는 도서 등 CreativeWork)의 식별자
   *
   * @minItems 1
   */
  isBasedOn: [TerminalIdentifier, ...TerminalIdentifier[]];
  [k: string]: unknown;
}
