// This file is auto-generated. Do not edit it manually.
// To update these types, run `pnpm run generate-types`

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Bibliographic Reaction Object (BRO)의 JSON-LD 네이티브 원시 스키마.
 */
export type BibliographicReactionObjectBROV10 = BroItemList | BroArticle | BroAbstract;
/**
 * UUID v4, v5, v7을 수용하는 정규화된 범용 고유 식별자 URN 포맷.
 */
export type UrnUuidOnly = string;
/**
 * RFC 3339 기반 타임스탬프 강제 규격. Z 또는 오프셋 명시를 누락한 경우 DB 데이터 오염으로 간주하여 인입을 차단함.
 */
export type StrictDateTime = string;
/**
 * [CREATOR_ENTITIES] 작성자 엔티티 다형성 계층. 공공 및 법인은 @id 강제 검증, 개인은 수집 파편화 대응을 위한 선택적 @id 허용, 익명은 추적 불가능한 작성자 데이터의 유실 방지 Fallback.
 */
export type CreatorRoot =
  | CreatorPerson
  | CreatorAnonymous
  | CreatorGovernment
  | CreatorCorporation
  | CreatorOrganization
  | CreatorSoftware;
/**
 * BCP 47 / ISO 639 언어 코드 목록.
 */
export type LanguageArray = string[];
/**
 * 분류용 핵심어 목록.
 */
export type KeywordsArray = string[];
/**
 * Schema.org 표준 PropertyValue 기반 동적 메타데이터 확장 컨테이너. 도서관이나 서비스별로 파편화된 커스텀 메타데이터(예: 평점, 완독 여부, 추천 연령 등)를 스키마를 오염시키지 않고 수용함. NoSQL이나 RDBMS의 JSON 컬럼에서 완벽한 기계적 인덱싱이 가능함.
 */
export type AdditionalPropertyArray = {
  "@type": "PropertyValue";
  /**
   * 동적 속성의 식별 키(Key)
   */
  name: string;
  /**
   * 동적 속성의 값(Value). 원시 타입 및 객체 허용.
   */
  value: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}[];
export type UrnIdentifier =
  | {
      [k: string]: unknown;
    }
  | {
      [k: string]: unknown;
    }
  | {
      [k: string]: unknown;
    }
  | {
      [k: string]: unknown;
    }
  | {
      [k: string]: unknown;
    }
  | {
      [k: string]: unknown;
    };
export type UrnIdentifier1 = string;
/**
 * 순수 본문 문자열 (주로 Markdown 구조). YAML Frontmatter 캡슐화를 전면 폐기함. 인입 파이프라인에서 본 필드 내의 메타데이터 은닉을 감지할 경우 페이로드 수용을 거부(Reject)하며, 모든 메타 속성은 JSON의 1급 객체 또는 additionalProperty로 분리 추출되어야 함.
 */
export type PureText = string;

/**
 * 다중 타겟 문서 큐레이션을 위한 영속적 컨테이너 엔티티 (ItemList).
 */
export interface BroItemList {
  "@context": "https://schema.org";
  "@type": "ItemList";
  "@id": UrnUuidOnly;
  /**
   * 리스트 컨테이너의 고유 명칭.
   */
  name?: string;
  dateCreated: StrictDateTime;
  /**
   * RFC 3339 기반 타임스탬프 강제 규격. Z 또는 오프셋 명시를 누락한 경우 DB 데이터 오염으로 간주하여 인입을 차단함.
   */
  dateModified?: string;
  /**
   * 에그리거트 루트의 변경 이력 추적 및 낙관적 락(Optimistic Locking) 검증을 위한 버전 해시 또는 시퀀스 넘버.
   */
  version?: string | number;
  /**
   * @minItems 1
   */
  creator: [CreatorRoot, ...CreatorRoot[]];
  /**
   * 리스트에 포함된 개별 문서(Article 등)의 식별자 목록. 직접 내포(Embedding) 금지. 데이터 단편화 방지 및 URN 식별자 정규화를 위해 철저히 포인터 기반 참조로 격리함.
   */
  itemListElement: {
    "@id": UrnUuidOnly;
    [k: string]: unknown;
  }[];
  inLanguage?: LanguageArray;
  keywords?: KeywordsArray;
  additionalProperty?: AdditionalPropertyArray;
  [k: string]: unknown;
}
export interface CreatorPerson {
  "@type": "Person";
  name: string;
  /**
   * 인증된 사용자에 한해 부여되는 URN/ORCID 식별자. 파편화된 외부 데이터 스크래핑 인입 시 생략을 허용함.
   */
  "@id"?:
    | UrnUuidOnly
    | {
        [k: string]: unknown;
      };
}
/**
 * 네트워크 인입 단말 혹은 수집 파이프라인에서 작성자 엔티티 추적에 실패할 경우, null/undefined로 인한 스키마 크래시를 방지하는 Fallback 타입.
 */
export interface CreatorAnonymous {
  "@type": "Anonymous";
  name?: string;
}
export interface CreatorGovernment {
  "@type": "GovernmentOrganization";
  name: string;
  "@id":
    | UrnUuidOnly
    | {
        [k: string]: unknown;
      };
}
export interface CreatorCorporation {
  "@type": "Corporation";
  name: string;
  "@id":
    | UrnUuidOnly
    | {
        [k: string]: unknown;
      };
}
export interface CreatorOrganization {
  "@type": "Organization";
  name: string;
  "@id":
    | UrnUuidOnly
    | {
        [k: string]: unknown;
      };
}
export interface CreatorSoftware {
  "@type": "SoftwareApplication";
  name: string;
  softwareVersion?: string;
  "@id": {
    [k: string]: unknown;
  };
}
/**
 * 단일 파생 문서(Article) 처리를 위한 영속성 스키마. 기존 YAML 프론트매터 속성을 스키마 최상위 프로퍼티로 추출하여 검색 엔진 및 DB 인덱서의 직접 접근을 허용함.
 */
export interface BroArticle {
  "@context": "https://schema.org";
  "@type": "Article";
  "@id": UrnUuidOnly;
  /**
   * 파생 문서 자체의 제목. 시스템 반환 시 Article 엔티티의 최상위 명칭으로 사용됨.
   */
  name?: string;
  /**
   * 현재 문서가 타겟팅(about)하고 있는 원본 코어 저작물의 텍스트 명칭(name). 원문 URN 참조가 실패하거나 지연 로딩될 경우의 디그레이드(Degrade) 처리를 위한 역정규화 데이터. 스키마 전역의 명명 규칙(Naming Convention) 통일성에 따라 Title 대신 Name을 접미사로 강제함.
   */
  aboutName?: string;
  /**
   * 현재 문서가 타겟팅하는 원본 코어 저작물의 원작자 텍스트 표기.
   */
  aboutCreator?: string;
  /**
   * 현재 파생 문서 작성자의 크레딧 라인 표기.
   */
  articleByline?: string;
  dateCreated: StrictDateTime;
  dateModified?: StrictDateTime;
  datePublished?: StrictDateTime;
  version?: string | number;
  /**
   * 파생 문서가 타겟팅하는 코어 저작물 엔티티의 식별자 묶음. 다중 판본 바인딩 시 복수 원소를 허용함.
   *
   * @minItems 1
   */
  about: [TerminalIdentifier, ...TerminalIdentifier[]];
  text: PureText;
  inLanguage?: LanguageArray;
  keywords?: KeywordsArray;
  /**
   * 관련 이미지 URL 배열.
   */
  image?: string[];
  /**
   * 참고 문헌 또는 원문 URL 목록.
   */
  citation?: string[];
  /**
   * 현재 문서(Article)에 종속된 파생 요약본의 식별자(URN) 배열. 1:N 구조의 디스크 중복 적재를 막기 위한 식별자 참조. 본문 내포 절대 금지.
   */
  abstract?: {
    "@id": UrnUuidOnly;
    [k: string]: unknown;
  }[];
  /**
   * @minItems 1
   */
  creator: [CreatorRoot, ...CreatorRoot[]];
  additionalProperty?: AdditionalPropertyArray;
  [k: string]: unknown;
}
/**
 * 순환 참조(Billion Laughs 등) 무한 루프 렌더링 공격을 원천 차단하기 위해 계층 깊이를 제한한 터미널 식별 객체.
 */
export interface TerminalIdentifier {
  "@type": "Article" | "CreativeWork";
  /**
   * [BASE_PRIMITIVES: 원시 데이터 계층 식별자] 시스템 레벨의 소문자 URN Scheme 정규화를 전제로 한 정규식 집합.
   */
  identifier: UrnIdentifier & UrnIdentifier1;
}
/**
 * 구조화된 요약 데이터. isBasedOn 속성을 통해 원본 역참조.
 */
export interface BroAbstract {
  "@context": "https://schema.org";
  "@type": "CreativeWork";
  "@id": UrnUuidOnly;
  /**
   * 요약 데이터의 텍스트 명칭(제목). 스키마 전역의 식별 표제 단일화 정책에 따라 name 속성을 할당함.
   */
  name?: string;
  dateCreated: StrictDateTime;
  dateModified?: StrictDateTime;
  version?: string | number;
  text: PureText;
  inLanguage?: LanguageArray;
  keywords?: KeywordsArray;
  /**
   * 관련 이미지 URL 배열.
   */
  image?: string[];
  /**
   * 참고 문헌 또는 원문 URL 목록.
   */
  citation?: string[];
  /**
   * @minItems 1
   */
  creator: [CreatorRoot, ...CreatorRoot[]];
  /**
   * 이 요약이 기반하고 있는 원본 엔티티(Article 또는 도서 등 CreativeWork)의 단방향 외부 식별자 포인터.
   *
   * @minItems 1
   */
  isBasedOn: [TerminalIdentifier, ...TerminalIdentifier[]];
  additionalProperty?: AdditionalPropertyArray;
  [k: string]: unknown;
}
